### PR TITLE
Onboarding page

### PR DESCRIPTION
**Pull request by Lizdev-05**
In this milestone, I achieved the following: 

- Created a folder and 3 sub-folders that hold the onboarding pages
- Completed the static page for the onboarding welcome
- Completed the static page for the onboarding team
- Completed the static page for the successful onboarding

What needs to be done
- Work on the successful onboarding to be modal
- Consume the API so that the pages can be functional

### CODE REVIEW

**Review by Samsonroyal — DISMISSED** [review]

**Comment by Samsonroyal** [comment]
@boypaida12 kindly review these changes

**Review by boypaida12 — DISMISSED** [review]

**Comment by Samsonroyal** [comment]
@Lizdev-05 please apply the earlier changes as discussed; this PR will be ready to merge; 

- Button on Landing Page
- The black space on onboardingTeam

**Review by bright2kwame — APPROVED** [review]
Great, let keep the naming convention

**Comment by Lizdev-05** [comment]
> @Lizdev-05 please apply the earlier changes as discussed; this PR will be ready to merge;
> 
> * Button on Landing Page
> * The black space on the onboarding team

Hello @Samsonroyal, kindly note that I have updated the code with the required changes. 
The changes include...

- Renamed the subfolders
- Removed the styling from the button component
- Removed the styling from the input component
- Styled the button and input props
Please review and merge.

**Comment by Samsonroyal** [comment]
> > @Lizdev-05 please apply the earlier changes as discussed; this PR will be ready to merge;
> > 
> > * Button on Landing Page
> > * The black space on the onboarding team
> 
> Hello @Samsonroyal, kindly note that I have updated the code with the required changes. The changes include...
> 
>     * Renamed the subfolders
> 
>     * Removed the styling from the button component
> 
>     * Removed the styling from the input component
> 
>     * Styled the button and input props
> 
>     * Removed the black space on the team page
>       Please review and merge.

Hello @Lizdev-05 let me test the changes locally then review accordingly

**Review by Samsonroyal — APPROVED** [review]
Good to merge

**Pull request merged**
