### PR TITLE
Create dashboard layout

### PR DESCRIPTION
**Pull request by xarrijorge**
I've created the sidebar and added it to the Dashboard layout. Please review and let me know the other tasks. I'm not so certain about that.

### CODE REVIEW

**Comment by Samsonroyal** [comment]
> I've created the sidebar and added it to the Dashboard layout. Please review and let me know the other tasks. I'm not so certain about that.

Awesome work and superhuman speed; @xarrijorge Let me test the changes locally then review accordingly. Will Merge if there's no further request or incremental tasks.

**Comment by Samsonroyal** [comment]
Hello @xarrijorge I have just fired up the dashboard. The width of the sidebar feels just right; and is supremely beautiful. Great work
however few changes are needed.

- The icons to use for the workspaces/stack and settings can be accessed here [ionicons](https://ionic.io/ionicons); search for layers-outline and cog-outline; use them as an svg
- the padding between each of the icons on the sidebar has to resonate with the figma design.
- The icon colour by default should be black; On hover a tooltip should appear for each of the icons, on click; the icon is selected and a green line beside icon tab should appear
- There's a faint line of colour that fades outward from where the menu icons are; please add it.

## Visual of faint gray line; it appears more with white bg color for main page
Terminal empty state light mode

**Review by Samsonroyal — CHANGES_REQUESTED** [review]
https://github.com/Samsonroyal/Clearpath/pull/25#issuecomment-2118445857

I requested some changes here

**Review by bright2kwame — APPROVED** [review]

**Comment by Samsonroyal** [comment]
Heyy @xarrijorge since the dashboard layout and sidenav are already merged into development branch; I am closing this PR as a duplicate.

**Pull request closed without merging**
