### PR TITLE
Created a task listing component

### PR DESCRIPTION
**Pull request by AJKossi**
1. Created a Task component which takes task like a type as input
2. Created TaskList component which takes Task[] as input

### CODE REVIEW

**Review by Samsonroyal — CHANGES_REQUESTED** [review]
Hello @AJKossi ; I just ran your code in my local environment; to see what the task card component you created looks like. This is what it looks like when rendered with an object of data. 
image

### Suggestions
1. Make the card longer; get the dimensions from the UI file;
2. Add an avatar icon at the top;
3. Restructure the object model to reflect the fields as seen on the card below 
4. Add the color ribbon at the left side
5. Ensure the border radius is similar to cards in the UI

I commend the great work and speed with which you are working however it does still need some changes till it attains pixel perfection as seen in the UI file [here ](https://www.figma.com/design/U8oqohTVdnlEn312GqrBEf/Clearpath?node-id=429-42501&t=9U1Dq0gSkg9hUJjL-0)

The task card has to look something like this
Frame 299

**Comment by Samsonroyal** [comment]
```
"use client";
import Task from "@/components/Task";
import { useRef, useState } from "react";

export default function Terminal() {
  const task = {
    id: 1,
    title: 'Sample Task',
    description: 'This is a sample task.',
    completed: false,
    date_start: new Date(), 
    date_end: new Date(),
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-4 text-gray-900"> 
      <Task task={task} />
    </main>
  );
}


```

the code above is what I ran to test out the card you made; it's the terminal route page

**Comment by AJKossi** [comment]
Now i created TaskCard and tested it.

**Review by Samsonroyal — APPROVED** [review]

**Comment by Samsonroyal** [comment]
@bright2kwame Please review the changes and then we'll proceed to merge

**Review by bright2kwame — APPROVED** [review]

**Pull request merged**
